#!/bin/bash

# Set the running environment
export HBNB_ENV="dev"  # Change to "test" or "production" as needed

# Set MySQL credentials
export HBNB_MYSQL_USER="hbnb_dev"
export HBNB_MYSQL_PWD="hbnb_dev_pwd"
export HBNB_MYSQL_HOST="localhost"
export HBNB_MYSQL_DB="hbnb_dev_db"

# Set the type of storage
export HBNB_TYPE_STORAGE="db"  # Change to "file" if using FileStorage
